openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://apit.test'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/lists/categories:
    get:
      summary: ''
      operationId: getApiListsCategories
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'ad qui earum'
                    -
                      id: 2
                      name: 'ut officiis sed'
                    -
                      id: 3
                      name: 'et id consequuntur'
                    -
                      id: 4
                      name: 'dolorem labore odit'
                    -
                      id: 5
                      name: 'quaerat aperiam omnis'
                    -
                      id: 6
                      name: 'atque blanditiis velit'
                    -
                      id: 7
                      name: 'et non esse'
                    -
                      id: 8
                      name: 'sit perspiciatis enim'
                    -
                      id: 9
                      name: 'rerum quo sit'
                    -
                      id: 10
                      name: 'molestias enim voluptates'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'ad qui earum'
                      -
                        id: 2
                        name: 'ut officiis sed'
                      -
                        id: 3
                        name: 'et id consequuntur'
                      -
                        id: 4
                        name: 'dolorem labore odit'
                      -
                        id: 5
                        name: 'quaerat aperiam omnis'
                      -
                        id: 6
                        name: 'atque blanditiis velit'
                      -
                        id: 7
                        name: 'et non esse'
                      -
                        id: 8
                        name: 'sit perspiciatis enim'
                      -
                        id: 9
                        name: 'rerum quo sit'
                      -
                        id: 10
                        name: 'molestias enim voluptates'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'ad qui earum'
      tags:
        - Endpoints
      security: []
  /api/categories:
    get:
      summary: ''
      operationId: getApiCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiCategories
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: laborum
                  nullable: false
              required:
                - name
      security: []
  '/api/categories/{id}':
    get:
      summary: ''
      operationId: getApiCategoriesId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: eaque
                  nullable: false
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
